# Generated by Django 6.0.5 on 2026-05-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('arquivo', models.URLField()),
                ('tipo', models.CharField(default='pdf', max_length=20)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['categoria', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Excecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('realocacao', 'Realocação de Fundos'), ('extensao', 'Extensão de Prazo'), ('aquisicao', 'Aquisição Emergencial')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('responsavel', models.CharField(max_length=200)),
                ('justificativa', models.TextField()),
                ('status', models.CharField(choices=[('aprovada', 'Aprovada'), ('pendente', 'Pendente'), ('reprovada', 'Reprovada')], default='pendente', max_length=20)),
                ('analisado_por', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Exceção',
                'verbose_name_plural': 'Exceções',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField()),
                ('conteudo', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('imagem', models.URLField(blank=True)),
                ('publicado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('periodo', models.CharField(max_length=100)),
                ('valor_aprovado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_executado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_disponivel', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('aprovado_por', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Protocolo',
                'verbose_name_plural': 'Protocolos',
                'ordering': ['-data'],
            },
        ),
    ]
