# Generated by Django 6.0.5 on 2026-05-20 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria/', verbose_name='Foto')),
                ('legenda', models.CharField(blank=True, max_length=200, verbose_name='Legenda / Alt text')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Visível no site')),
            ],
            options={
                'verbose_name': 'Foto da Galeria',
                'verbose_name_plural': 'Galeria de Fotos',
                'ordering': ['ordem'],
            },
        ),
        migrations.AlterModelOptions(
            name='excecao',
            options={'ordering': ['-data'], 'verbose_name': 'Exceção / Desvio', 'verbose_name_plural': 'Exceções / Desvios'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['nome'], 'verbose_name': 'Projeto de Transparência', 'verbose_name_plural': 'Projetos de Transparência'},
        ),
        migrations.AddField(
            model_name='noticia',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('planejado', 'Planejado')], default='em_andamento', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(upload_to='documentos/', verbose_name='Arquivo (PDF)'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('ata', 'Ata'), ('contrato', 'Contrato'), ('mapa', 'Mapa'), ('relatorio', 'Relatório'), ('outro', 'Outro')], default='outro', max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(default='pdf', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='excecao',
            name='analisado_por',
            field=models.CharField(blank=True, max_length=200, verbose_name='Analisado por'),
        ),
        migrations.AlterField(
            model_name='excecao',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='excecao',
            name='justificativa',
            field=models.TextField(verbose_name='Justificativa'),
        ),
        migrations.AlterField(
            model_name='excecao',
            name='responsavel',
            field=models.CharField(max_length=200, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='excecao',
            name='status',
            field=models.CharField(choices=[('aprovada', 'Aprovada'), ('pendente', 'Pendente'), ('reprovada', 'Reprovada')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='excecao',
            name='tipo',
            field=models.CharField(choices=[('realocacao', 'Realocação de Fundos'), ('extensao', 'Extensão de Prazo'), ('aquisicao', 'Aquisição Emergencial')], max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='excecao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('assinaturas', 'Assinaturas'), ('construcao', 'Construção'), ('producao', 'Produção'), ('credito', 'Crédito'), ('eventos', 'Eventos'), ('geral', 'Geral')], default='geral', max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo (HTML)'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateField(verbose_name='Data de Publicação'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='publicado',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='resumo',
            field=models.TextField(verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do Projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='periodo',
            field=models.CharField(max_length=100, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='saldo_disponivel',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Disponível (R$)'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='valor_aprovado',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Aprovado (R$)'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='valor_executado',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Executado (R$)'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='aprovado_por',
            field=models.CharField(max_length=200, verbose_name='Aprovado por'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='numero',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)'),
        ),
        migrations.CreateModel(
            name='LinhaOrcamentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor_aprovado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Aprovado (R$)')),
                ('valor_executado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Executado (R$)')),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('em_andamento', 'Em Andamento'), ('planejado', 'Planejado')], default='planejado', max_length=20, verbose_name='Status')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='api.projeto', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Linha Orçamentária',
                'verbose_name_plural': 'Linhas Orçamentárias',
            },
        ),
    ]
